"""
Blender Script: Bake Base Color Texture to Vertex Colors
Version: 1.0.0
Blender: 5.0+

This script bakes base color textures from materials to vertex color attributes
using Cycles rendering engine. It preserves all original textures and material
states, using temporary images for the baking process.

Usage:
1. Select mesh objects with materials
2. Run script in Blender's Text Editor or via command line
3. Check console for detailed progress and results

Author: Generated by Claude Code
Date: 2026-01-07
"""

import bpy
import time
from typing import Dict, List, Tuple, Optional


class BakeLogger:
    """Handles detailed logging for the baking process"""

    def __init__(self):
        self.indent_level = 0
        self.start_time = time.time()

    def log(self, message: str, level: str = "INFO"):
        """Log a message with timestamp and indentation"""
        indent = "  " * self.indent_level
        elapsed = time.time() - self.start_time
        print(f"[{elapsed:7.2f}s] {level:8s} {indent}{message}")

    def info(self, message: str):
        """Log info message"""
        self.log(message, "INFO")

    def warning(self, message: str):
        """Log warning message"""
        self.log(message, "WARNING")

    def error(self, message: str):
        """Log error message"""
        self.log(message, "ERROR")

    def success(self, message: str):
        """Log success message"""
        self.log(message, "SUCCESS")

    def indent(self):
        """Increase indentation level"""
        self.indent_level += 1

    def dedent(self):
        """Decrease indentation level"""
        self.indent_level = max(0, self.indent_level - 1)


logger = BakeLogger()


def validate_object(obj: bpy.types.Object) -> Tuple[bool, Optional[str]]:
    """
    Validate if object is suitable for texture to vertex color baking

    Args:
        obj: Blender object to validate

    Returns:
        Tuple of (is_valid, error_reason)
    """
    logger.info(f"Validating object: {obj.name}")
    logger.indent()

    # Check if mesh
    if obj.type != 'MESH':
        reason = f"Not a mesh object (type: {obj.type})"
        logger.warning(reason)
        logger.dedent()
        return False, reason

    logger.info(f"Object type: MESH ✓")

    # Check has mesh data
    if not obj.data:
        reason = "No mesh data"
        logger.error(reason)
        logger.dedent()
        return False, reason

    # Check has UV map
    if not obj.data.uv_layers or len(obj.data.uv_layers) == 0:
        reason = "No UV maps found"
        logger.warning(reason)
        logger.dedent()
        return False, reason

    uv_layer_name = obj.data.uv_layers.active.name if obj.data.uv_layers.active else obj.data.uv_layers[0].name
    logger.info(f"Active UV layer: {uv_layer_name} ✓")

    # Check has materials
    if not obj.material_slots or len(obj.material_slots) == 0:
        reason = "No material slots"
        logger.warning(reason)
        logger.dedent()
        return False, reason

    logger.info(f"Material slots: {len(obj.material_slots)}")

    # Check at least one material has node tree with base color texture
    has_valid_material = False
    for idx, slot in enumerate(obj.material_slots):
        mat = slot.material
        if not mat:
            logger.warning(f"  Slot {idx}: Empty")
            continue

        if not mat.use_nodes or not mat.node_tree:
            logger.warning(f"  Slot {idx} ({mat.name}): No node tree")
            continue

        # Check for base color texture
        has_texture = check_material_has_base_color_texture(mat)
        if has_texture:
            logger.info(f"  Slot {idx} ({mat.name}): Base color texture found ✓")
            has_valid_material = True
        else:
            logger.warning(f"  Slot {idx} ({mat.name}): No base color texture")

    if not has_valid_material:
        reason = "No materials with base color textures"
        logger.warning(reason)
        logger.dedent()
        return False, reason

    logger.success(f"Object {obj.name} is valid for baking")
    logger.dedent()
    return True, None


def check_material_has_base_color_texture(material: bpy.types.Material) -> bool:
    """
    Check if material has a base color texture connected

    Args:
        material: Blender material to check

    Returns:
        True if base color texture found
    """
    if not material.use_nodes or not material.node_tree:
        return False

    # Find output node
    output_node = None
    for node in material.node_tree.nodes:
        if node.type == 'OUTPUT_MATERIAL':
            output_node = node
            break

    if not output_node:
        return False

    # Traverse from output to find shader node with base color
    surface_input = output_node.inputs.get('Surface')
    if not surface_input or not surface_input.links:
        return False

    shader_node = surface_input.links[0].from_node

    # Check for base color input (Principled BSDF, Diffuse BSDF, etc.)
    base_color_input = None
    if 'Base Color' in shader_node.inputs:
        base_color_input = shader_node.inputs['Base Color']
    elif 'Color' in shader_node.inputs:
        base_color_input = shader_node.inputs['Color']

    if not base_color_input or not base_color_input.links:
        return False

    # Check if connected to an image texture
    connected_node = base_color_input.links[0].from_node
    return connected_node.type == 'TEX_IMAGE' and connected_node.image is not None


def store_material_state(obj: bpy.types.Object) -> Dict:
    """
    Store original material state for restoration

    Args:
        obj: Object whose materials to store

    Returns:
        Dictionary of material states
    """
    logger.info(f"Storing material state for {obj.name}")
    logger.indent()

    state = {}
    for slot in obj.material_slots:
        mat = slot.material
        if not mat or not mat.use_nodes or not mat.node_tree:
            continue

        active_node = mat.node_tree.nodes.active
        logger.info(f"Material '{mat.name}': Active node = {active_node.name if active_node else 'None'}")

        state[mat] = {
            'original_active_node': active_node,
            'temp_texture_node': None
        }

    logger.dedent()
    return state


def create_bake_target(obj: bpy.types.Object, material_state: Dict, resolution: int = 2048) -> Optional[bpy.types.Image]:
    """
    Create temporary bake image and setup temp nodes in materials

    Args:
        obj: Object to setup bake for
        material_state: Material state dictionary to update
        resolution: Bake image resolution

    Returns:
        Temporary bake image or None on failure
    """
    logger.info(f"Creating bake target for {obj.name}")
    logger.indent()

    # Create unique temp image
    timestamp = int(time.time())
    image_name = f"_TEMP_BAKE_{obj.name}_{timestamp}"

    logger.info(f"Creating temp image: {image_name} ({resolution}x{resolution})")
    temp_image = bpy.data.images.new(
        name=image_name,
        width=resolution,
        height=resolution,
        alpha=True,
        float_buffer=False  # 8-bit is sufficient for vertex colors
    )

    # Setup temp node in each material
    materials_with_nodes = 0
    for mat, state in material_state.items():
        if not mat.use_nodes or not mat.node_tree:
            continue

        logger.info(f"Adding temp node to material: {mat.name}")

        # Create temp image texture node
        temp_node = mat.node_tree.nodes.new('ShaderNodeTexImage')
        temp_node.name = f"_TEMP_BAKE_NODE_{timestamp}"
        temp_node.label = "TEMP BAKE TARGET"
        temp_node.image = temp_image
        temp_node.location = (0, 0)  # Doesn't matter, won't be visible

        # Set as active node (CRITICAL for bake target)
        mat.node_tree.nodes.active = temp_node

        # Store reference for cleanup
        state['temp_texture_node'] = temp_node
        materials_with_nodes += 1

        logger.info(f"  Set '{temp_node.name}' as active node")

    logger.success(f"Bake target setup complete ({materials_with_nodes} materials)")
    logger.dedent()

    return temp_image


def bake_object_textures(obj: bpy.types.Object) -> bool:
    """
    Execute Cycles bake operation

    Args:
        obj: Object to bake

    Returns:
        True if bake succeeded
    """
    logger.info(f"Starting Cycles bake for {obj.name}")
    logger.indent()

    # Ensure object is selected and active
    bpy.ops.object.select_all(action='DESELECT')
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj

    logger.info("Object selection: Active ✓")

    # Ensure in object mode
    if obj.mode != 'OBJECT':
        logger.info(f"Switching from {obj.mode} mode to OBJECT mode")
        bpy.ops.object.mode_set(mode='OBJECT')

    # Configure bake settings
    logger.info("Configuring bake settings:")
    logger.indent()
    logger.info("Type: DIFFUSE")
    logger.info("Pass filter: COLOR only")
    logger.info("Clear: True")
    logger.info("Margin: 0")
    logger.dedent()

    try:
        # Execute bake
        logger.info("Executing bpy.ops.object.bake()...")
        bake_start = time.time()

        bpy.ops.object.bake(
            type='DIFFUSE',
            pass_filter={'COLOR'},
            use_clear=True,
            margin=0
        )

        bake_duration = time.time() - bake_start
        logger.success(f"Bake completed in {bake_duration:.2f}s")
        logger.dedent()
        return True

    except Exception as e:
        logger.error(f"Bake failed: {str(e)}")
        logger.dedent()
        return False


def transfer_to_vertex_colors(obj: bpy.types.Object, baked_image: bpy.types.Image) -> bool:
    """
    Transfer baked image to vertex color attribute

    Args:
        obj: Object to add vertex colors to
        baked_image: Baked image to sample from

    Returns:
        True if transfer succeeded
    """
    logger.info(f"Transferring baked texture to vertex colors")
    logger.indent()

    mesh = obj.data

    # Create or replace Color attribute
    logger.info("Setting up 'color' vertex color attribute")
    if "color" in mesh.color_attributes:
        logger.info("  Removing existing 'color' attribute")
        mesh.color_attributes.remove(mesh.color_attributes["color"])

    logger.info("  Creating new 'color' attribute (VERTEX domain, BYTE_COLOR)")
    color_attr = mesh.color_attributes.new(
        name="color",
        type='BYTE_COLOR',
        domain='POINT'  # POINT is the API name for VERTEX domain
    )

    # Get UV layer
    if not mesh.uv_layers.active:
        logger.error("No active UV layer")
        logger.dedent()
        return False

    uv_layer = mesh.uv_layers.active
    logger.info(f"Using UV layer: {uv_layer.name}")

    # Get image dimensions and pixel data
    width, height = baked_image.size
    logger.info(f"Baked image size: {width}x{height}")
    logger.info("Loading pixel data...")

    pixels = baked_image.pixels[:]  # Load entire pixel buffer
    logger.info(f"Loaded {len(pixels)} pixel values ({len(pixels)//4} pixels)")

    # Transfer colors
    logger.info(f"Transferring colors to {len(mesh.loops)} loops...")
    transfer_start = time.time()

    for loop_idx, loop in enumerate(mesh.loops):
        # Get UV coordinate for this loop
        uv = uv_layer.data[loop_idx].uv

        # Convert UV (0-1) to pixel coordinates
        # Clamp to avoid edge issues
        u = max(0.0, min(0.9999, uv.x))
        v = max(0.0, min(0.9999, uv.y))

        x = int(u * width)
        y = int(v * height)

        # Get pixel color (RGBA) from linear pixel array
        pixel_index = (y * width + x) * 4
        r = pixels[pixel_index]
        g = pixels[pixel_index + 1]
        b = pixels[pixel_index + 2]
        a = pixels[pixel_index + 3]

        # Assign to vertex color attribute
        color_attr.data[loop_idx].color = (r, g, b, a)

    transfer_duration = time.time() - transfer_start
    logger.success(f"Transfer completed in {transfer_duration:.2f}s ({len(mesh.loops)} loops)")

    # Update mesh
    mesh.update()
    logger.info("Mesh updated")

    logger.dedent()
    return True


def cleanup_bake_data(temp_image: bpy.types.Image, material_state: Dict):
    """
    Clean up temporary bake data and restore material state

    Args:
        temp_image: Temporary bake image to remove
        material_state: Material state to restore
    """
    logger.info("Cleaning up bake data")
    logger.indent()

    # Restore material states and remove temp nodes
    for mat, state in material_state.items():
        if not mat.use_nodes or not mat.node_tree:
            continue

        logger.info(f"Restoring material: {mat.name}")

        # Remove temp node
        temp_node = state['temp_texture_node']
        if temp_node and temp_node.name in mat.node_tree.nodes:
            logger.info(f"  Removing temp node: {temp_node.name}")
            mat.node_tree.nodes.remove(temp_node)

        # Restore original active node
        original_active = state['original_active_node']
        if original_active and original_active.name in mat.node_tree.nodes:
            mat.node_tree.nodes.active = original_active
            logger.info(f"  Restored active node: {original_active.name}")
        else:
            mat.node_tree.nodes.active = None
            logger.info(f"  Cleared active node (was None)")

    # Remove temp image
    if temp_image and temp_image.name in bpy.data.images:
        logger.info(f"Removing temp image: {temp_image.name}")
        bpy.data.images.remove(temp_image)

    logger.success("Cleanup complete")
    logger.dedent()


def bake_textures_to_vertex_colors(bake_resolution: int = 2048):
    """
    Main function to bake textures to vertex colors for selected objects

    Args:
        bake_resolution: Resolution of temporary bake image
    """
    logger.info("=" * 80)
    logger.info("BAKE TEXTURES TO VERTEX COLORS - START")
    logger.info("=" * 80)
    logger.info(f"Blender version: {bpy.app.version_string}")
    logger.info(f"Bake resolution: {bake_resolution}x{bake_resolution}")
    logger.info("")

    # Store original render engine
    original_engine = bpy.context.scene.render.engine
    logger.info(f"Current render engine: {original_engine}")

    # Switch to Cycles if needed
    if original_engine != 'CYCLES':
        logger.info("Switching to CYCLES render engine")
        bpy.context.scene.render.engine = 'CYCLES'
    else:
        logger.info("Already using CYCLES ✓")

    logger.info("")

    # Get selected objects
    selected_objects = [obj for obj in bpy.context.selected_objects]
    logger.info(f"Selected objects: {len(selected_objects)}")

    if not selected_objects:
        logger.warning("No objects selected!")
        logger.info("=" * 80)
        return

    logger.info("")

    # Filter and validate objects
    logger.info("Validating objects...")
    logger.info("-" * 80)
    logger.indent()

    valid_objects = []
    skipped_objects = []

    for obj in selected_objects:
        is_valid, reason = validate_object(obj)
        if is_valid:
            valid_objects.append(obj)
        else:
            skipped_objects.append({'object': obj, 'reason': reason})
        logger.info("")

    logger.dedent()
    logger.info("-" * 80)
    logger.info(f"Valid objects: {len(valid_objects)}")
    logger.info(f"Skipped objects: {len(skipped_objects)}")
    logger.info("")

    # Process valid objects
    processed_objects = []
    failed_objects = []

    for idx, obj in enumerate(valid_objects):
        logger.info("=" * 80)
        logger.info(f"Processing object {idx + 1}/{len(valid_objects)}: {obj.name}")
        logger.info("=" * 80)
        logger.indent()

        material_state = None
        temp_image = None

        try:
            # Store material state
            material_state = store_material_state(obj)
            logger.info("")

            # Create bake target
            temp_image = create_bake_target(obj, material_state, bake_resolution)
            if not temp_image:
                raise Exception("Failed to create bake target")
            logger.info("")

            # Bake
            bake_success = bake_object_textures(obj)
            if not bake_success:
                raise Exception("Bake operation failed")
            logger.info("")

            # Transfer to vertex colors
            transfer_success = transfer_to_vertex_colors(obj, temp_image)
            if not transfer_success:
                raise Exception("Transfer to vertex colors failed")
            logger.info("")

            # Success
            processed_objects.append(obj)
            logger.success(f"Object '{obj.name}' processed successfully!")

        except Exception as e:
            logger.error(f"Failed to process object '{obj.name}': {str(e)}")
            failed_objects.append({'object': obj, 'error': str(e)})

        finally:
            # Always cleanup
            if material_state and temp_image:
                cleanup_bake_data(temp_image, material_state)
                logger.info("")

        logger.dedent()
        logger.info("")

    # Restore original render engine
    if original_engine != bpy.context.scene.render.engine:
        logger.info(f"Restoring render engine to: {original_engine}")
        bpy.context.scene.render.engine = original_engine

    logger.info("")

    # Final report
    logger.info("=" * 80)
    logger.info("BAKE COMPLETE - SUMMARY")
    logger.info("=" * 80)
    logger.info(f"Total selected: {len(selected_objects)}")
    logger.info(f"Successfully processed: {len(processed_objects)}")
    logger.info(f"Failed: {len(failed_objects)}")
    logger.info(f"Skipped: {len(skipped_objects)}")
    logger.info("")

    if processed_objects:
        logger.info("Processed objects:")
        logger.indent()
        for obj in processed_objects:
            logger.info(f"✓ {obj.name}")
        logger.dedent()
        logger.info("")

    if failed_objects:
        logger.info("Failed objects:")
        logger.indent()
        for item in failed_objects:
            logger.error(f"✗ {item['object'].name}: {item['error']}")
        logger.dedent()
        logger.info("")

    if skipped_objects:
        logger.info("Skipped objects:")
        logger.indent()
        for item in skipped_objects:
            logger.warning(f"⊘ {item['object'].name}: {item['reason']}")
        logger.dedent()
        logger.info("")

    total_time = time.time() - logger.start_time
    logger.info(f"Total execution time: {total_time:.2f}s")
    logger.info("=" * 80)


# Run the script
if __name__ == "__main__":
    bake_textures_to_vertex_colors(bake_resolution=2048)
