// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';

import type { StoryblokMultilink, StoryblokRichtext, StoryblokAsset } from '../storyblok.d.ts';
export interface Article {
  title?: string;
  content?: StoryblokRichtext;
  media?: StoryblokAsset;
  excerpt?: string;
  category?: ISbStoryData<Category> | string;
  component: "article";
  _uid: string;
  [k: string]: unknown;
}

export interface Category {
  name?: string;
  icon?: string;
  component: "category";
  _uid: string;
  [k: string]: unknown;
}

export interface CodepenEmbed {
  penId: string;
  author: string;
  component: "codepen-embed";
  _uid: string;
  [k: string]: unknown;
}

export interface ErrorState {
  title?: string;
  message?: StoryblokRichtext;
  component: "error-state";
  _uid: string;
  [k: string]: unknown;
}

export interface FeaturedHero {
  headline?: string;
  story: (Article | Project)[];
  component: "featured-hero";
  _uid: string;
  [k: string]: unknown;
}

export interface GithubEmbed {
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "github-embed";
  _uid: string;
  [k: string]: unknown;
}

export interface HomeHero {
  title?: StoryblokRichtext;
  content?: StoryblokRichtext;
  socialLinks?: SocialLink[];
  modal?: unknown;
  contactBtnLabel?: string;
  modalTitle?: string;
  modalText?: StoryblokRichtext;
  modalSubmitLabel?: string;
  modalSubmitMessage?: StoryblokRichtext;
  component: "home-hero";
  _uid: string;
  [k: string]: unknown;
}

export interface LazyTheRepos {
  title?: string;
  sponsorLabel?: string;
  githubLabel?: string;
  errorState?: string;
  component: "lazy-the-repos";
  _uid: string;
  [k: string]: unknown;
}

export interface LazyTheVideos {
  title?: string;
  youtubeLabel?: string;
  errorState?: string;
  component: "lazy-the-videos";
  _uid: string;
  [k: string]: unknown;
}

export interface Overview {
  title?: string;
  featured_title?: string;
  featured_story: ISbStoryData<Article> | ISbStoryData<Project> | string;
  featured_cta_label?: string;
  read_more_cta_label?: string;
  order?: string;
  error_state?: ErrorState[];
  component: "overview";
  _uid: string;
  [k: string]: unknown;
}

export interface Playground {
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "playground";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  title: string;
  media?: StoryblokAsset;
  date?: string;
  active?: boolean;
  excerpt?: string;
  category: {
    [k: string]: unknown;
  };
  content?: StoryblokRichtext;
  featured?: boolean;
  component: "project";
  _uid: string;
  [k: string]: unknown;
}

export interface ScrollSection {
  content?: StoryblokRichtext;
  actions?: TheButton[];
  component: "scroll-section";
  _uid: string;
  [k: string]: unknown;
}

export interface SketchfabEmbed {
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "sketchfab-embed";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialLink {
  icon: "" | "twitter" | "github" | "dev-to" | "youtube";
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "social-link";
  _uid: string;
  [k: string]: unknown;
}

export interface StackblitzEmbed {
  projectId: string;
  file?: string;
  preview?: boolean;
  component: "stackblitz-embed";
  _uid: string;
  [k: string]: unknown;
}

export interface Talk {
  title?: string;
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  media?: StoryblokAsset;
  date?: string;
  excerpt?: string;
  event?: unknown;
  event_name?: string;
  event_url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  slides?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "talk";
  _uid: string;
  [k: string]: unknown;
}

export interface TextImage {
  media?: StoryblokAsset;
  direction?: "" | "row" | "reverse";
  content?: StoryblokRichtext;
  component: "text-image";
  _uid: string;
  [k: string]: unknown;
}

export interface TheButton {
  label?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  variant?: "" | "primary" | "secondary";
  outline?: boolean;
  flat?: boolean;
  component: "the-button";
  _uid: string;
  [k: string]: unknown;
}

export interface TheFooter {
  socialLinks?: SocialLink[];
  author?: string;
  years?: string;
  text?: StoryblokRichtext;
  component: "the-footer";
  _uid: string;
  [k: string]: unknown;
}

export interface TheHeader {
  headline?: string;
  component: "the-header";
  _uid: string;
  [k: string]: unknown;
}

export interface TheHero {
  title?: string;
  content?: StoryblokRichtext;
  reverse?: boolean;
  slot?: StoryblokRichtext;
  component: "the-hero";
  _uid: string;
  [k: string]: unknown;
}

export interface ThePage {
  body?: (
    | Article
    | Category
    | CodepenEmbed
    | ErrorState
    | FeaturedHero
    | GithubEmbed
    | HomeHero
    | LazyTheRepos
    | LazyTheVideos
    | Overview
    | Playground
    | Project
    | ScrollSection
    | SketchfabEmbed
    | SocialLink
    | StackblitzEmbed
    | Talk
    | TextImage
    | TheButton
    | TheFooter
    | TheHeader
    | TheHero
    | ThePage
    | TheUse
    | TwitterEmbed
  )[];
  order?: string;
  model?: StoryblokAsset;
  component: "the-page";
  _uid: string;
  [k: string]: unknown;
}

export interface TheUse {
  title?: string;
  icon?: "" | "code" | "term" | "lamp" | "brush";
  content?: StoryblokRichtext;
  component: "the-use";
  _uid: string;
  [k: string]: unknown;
}

export interface TwitterEmbed {
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  embed?: string;
  component: "twitter-embed";
  _uid: string;
  [k: string]: unknown;
}
